#!/bin/sh
PREREQ=""
prereqs()
{
    echo "$PREREQ"
}
case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

# Force copy the SOF topology file
# We copy the MTL topology which is referenced by our modprobe config

mkdir -p $DESTDIR/lib/firmware/intel/sof-ace-tplg
cp -f /lib/firmware/intel/sof-ace-tplg/sof-mtl-rt722-l0.tplg $DESTDIR/lib/firmware/intel/sof-ace-tplg/

